// Re-export grouped type modules for clearer organization
// Explicit type-only re-exports to satisfy `verbatimModuleSyntax` and keep imports stable
export type {
	ChartSource,
	ChartType,
	KPIMetric,
	ChartStatus,
	StatCardColor,
	StepStatus,
	InstanceStatus,
	RecoveryOutcome,
	ChartColors,
	ChartThresholds,
	CustomChart,
	StatCardProps,
	TrendPoint,
	WorkingHoursConfig,
} from "./common";

export type {
	RunningDocument,
	RunningDocumentsResponse,
	RunningDocumentsApiResponse,
	ActiveOverdueTask,
	ActiveOverdueTasksResponse,
	UserPerformanceItem,
	UserPerformanceResponse,
	SLADistributionPoint,
	SLADistributionResponse,
	BottleneckWorkflow,
	BottleneckWorkflowsResponse,
	BottleneckStep,
	BottleneckItem,
	UserSLA,
	RunningDocumentsDetailsProps,
	ActiveTasksDetailsProps,
	CompletedTasksResponse,
	SLAComplianceResponse,
} from "./overall";

export type {
	WorkflowStep,
	RecoveryStep,
	InstanceDetail,
	InstanceSummary,
	TotalInstancesResponse,
	AvgCompletionTimeResponse,
	WorkflowStepFlowResponse,
	WorkflowInstanceItem,
	WorkflowInstancesResponse,
	WorkflowListItem,
	WorkflowListResponse,
	WorkflowTotalInstancesValueResponse,
	WorkflowAvgCompletionTimeApiResponse,
	WorkflowSLAComplianceApiResponse,
	WorkflowInstance,
	WorkflowInstancesApiResponse,
	InstanceDrilldownTask,
	InstanceDrilldownResponse,
	WorkflowStepDetail,
	WorkflowStepFlowDetailResponse,
} from "./workflow";